const $=s=>document.querySelector(s), app=$('#app');
const KEY='shernzz-v03';
let db=JSON.parse(localStorage.getItem(KEY)||'null')||{customers:[],selected:null};
const save=()=>localStorage.setItem(KEY,JSON.stringify(db));
const esc=s=>(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const id=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,6);
const customerById=x=>db.customers.find(c=>c.id===x);
const current=()=>customerById(db.selected);
function chrome(){return `<span class="spark s1">✦</span><span class="spark s2">✧</span><span class="spark s3">✦</span><div class="brand"><div class="monogram">SC</div><div class="brandname">SHERNZZ</div><div class="brandsub">CREATIONS & CO</div></div>`}
function newCustomer(name,phone){let c={id:id(),name:name||'Shernzz Customer',phone:phone||'',stamps:0,history:[],redeemed:{5:false,10:false},created:new Date().toISOString()};db.customers.push(c);db.selected=c.id;save();return c}
function join(){app.innerHTML=`<div class="shell">${chrome()}<section class="panel hero"><div class="eyebrow">Loyalty Rewards</div><div class="big">Join the Shernzz family 💕</div><p class="muted">Shop. Create. Get rewarded. Collect 10 hearts and unlock exclusive Shernzz rewards.</p><label class="label">First name</label><input id="name" class="input" autocomplete="name" placeholder="Your name"><label class="label">Phone number</label><input id="phone" class="input" inputmode="tel" autocomplete="tel" placeholder="Your phone number"><button class="btn" id="join">Create my loyalty card</button><button class="btn secondary" id="staffJoinBtn">Staff dashboard</button><div class="tiny">V0.3 prototype — real SMS verification and secure staff login come when we connect the live service.</div></section><div class="footer">Shernzz Loyalty • V0.3</div></div>`;$('#join').onclick=()=>{newCustomer($('#name').value.trim(),$('#phone').value.trim());customer()};$('#staffJoinBtn').addEventListener('click',()=>staff())}
function hearts(c){return Array.from({length:10},(_,i)=>`<div class="heart ${i<c.stamps?'on':''}">♥</div>`).join('')}
function rewardState(c,n){return c.stamps>=n&&!c.redeemed[n]?'Available':c.redeemed[n]?'Redeemed':'Locked'}
function customer(){const c=current();if(!c)return join();const next=c.stamps<5?`${5-c.stamps} more order${5-c.stamps===1?'':'s'} → 25% OFF`:c.stamps<10?`${10-c.stamps} more order${10-c.stamps===1?'':'s'} → 50% OFF`:'All stamp milestones reached ✨';const latest=c.history[0];const celebrate=latest&&latest.type==='stamp'&&(latest.number===5||latest.number===10)&&!latest.seen; if(celebrate){latest.seen=true;save()}app.innerHTML=`<div class="shell">${chrome()}${celebrate?`<section class="panel celebrate"><div class="gift">🎁</div><div class="eyebrow">Congratulations!</div><div class="big">Reward unlocked</div><div class="ticket">${latest.number===10?'50% OFF':'25% OFF'}</div><p class="muted">You reached your ${latest.number===10?'10th':'5th'} order reward.</p></section>`:''}<section class="panel loyalty"><div class="welcome">Welcome back, 💕</div><div class="name">${esc(c.name)} ✨</div><div class="eyebrow">Your Loyalty Card</div><div class="hearts">${hearts(c)}</div><div class="progress">${c.stamps} / 10 orders</div><div class="next"><b>🎁 Next reward</b><br>${next}</div><div class="rewardgrid"><div class="reward ${c.stamps>=5?'unlocked':''}"><div class="status">${c.redeemed[5]?'✓':c.stamps>=5?'🎉':'🔒'}</div><b>5th order</b><small>25% OFF • ${rewardState(c,5)}</small></div><div class="reward ${c.stamps>=10?'unlocked':''}"><div class="status">${c.redeemed[10]?'✓':c.stamps>=10?'🎉':'🔒'}</div><b>10th order</b><small>50% OFF • ${rewardState(c,10)}</small></div></div></section><section class="panel"><div class="eyebrow">My activity</div>${historyHtml(c,false)}</section><div class="nav"><button id="staffCustomerBtn">Staff demo</button><button id="joinanother">Join another customer</button></div><div class="footer">Tap • Shop • Get rewarded</div></div>`;$('#staffCustomerBtn').addEventListener('click',()=>staff());$('#joinanother').addEventListener('click',()=>join())}
function historyHtml(c,staffView=true){if(!c.history.length)return '<p class="muted">No activity yet.</p>';return c.history.map(h=>`<div class="history"><span>${h.type==='stamp'?'💗':h.type==='redeem'?'🎁':'✨'} ${h.type==='stamp'?`Stamp #${h.number}`:h.label}</span><small>${esc(new Date(h.at).toLocaleString())}</small></div>`).join('')}
function staff(filter=''){const q=filter.toLowerCase();const list=db.customers.filter(c=>(c.name+' '+c.phone).toLowerCase().includes(q));app.innerHTML=`<div class="shell">${chrome()}<div class="topbar"><div><div class="eyebrow">Shernzz Loyalty</div><div class="big" style="font-size:27px">Staff Dashboard</div></div><span class="pill">PRIVATE</span></div><input id="search" class="search" placeholder="Search by name or phone number" value="${esc(filter)}"><section class="panel"><div class="eyebrow">Customers • ${db.customers.length}</div><div id="customerlist">${list.length?list.map(c=>`<button class="customerpick" data-id="${c.id}"><span class="avatar">${esc(c.name.slice(0,1).toUpperCase())}</span><span class="grow"><b>${esc(c.name)}</b><small>${esc(c.phone||'No phone entered')}</small></span><b>${c.stamps}/10</b></button>`).join(''):'<p class="muted">No matching customers.</p>'}</div><button class="btn secondary" id="new">+ Add / test new customer</button></section><button class="btn secondary" id="backToCard">← Back to customer card</button><div class="footer">V0.3.1 demo • Staff permissions are simulated locally for now.</div></div>`;$('#search').oninput=e=>staff(e.target.value);document.querySelectorAll('.customerpick').forEach(b=>b.onclick=()=>{db.selected=b.dataset.id;save();staffCustomer()});$('#new').onclick=join;$('#backToCard').onclick=customer}
function staffCustomer(){const c=current();if(!c)return staff();const avail5=c.stamps>=5&&!c.redeemed[5],avail10=c.stamps>=10&&!c.redeemed[10];app.innerHTML=`<div class="shell">${chrome()}<div class="topbar"><div><div class="eyebrow">Customer Details</div><div class="big" style="font-size:27px">${esc(c.name)}</div><div class="muted">${esc(c.phone||'No phone entered')}</div></div><span class="pill">${c.stamps}/10</span></div><section class="panel"><div class="hearts">${hearts(c)}</div><div class="progress">${c.stamps} / 10 orders</div><button class="btn" id="add" ${c.stamps>=10?'disabled':''}>+ Add Stamp</button>${avail5?`<button class="btn redeem" data-r="5">Redeem 25% Reward</button>`:''}${avail10?`<button class="btn redeem" data-r="10">Redeem 50% Reward</button>`:''}<button class="btn secondary" id="view">View Customer Card</button><button class="btn secondary" id="back">← All Customers</button></section><section class="panel"><div class="eyebrow">Rewards</div><div class="rewardgrid"><div class="reward ${c.stamps>=5?'unlocked':''}"><b>5th • 25% OFF</b><small>${rewardState(c,5)}</small></div><div class="reward ${c.stamps>=10?'unlocked':''}"><b>10th • 50% OFF</b><small>${rewardState(c,10)}</small></div></div></section><section class="panel"><div class="eyebrow">Activity</div>${historyHtml(c)}</section></div>`;$('#add').onclick=()=>{if(c.stamps<10){c.stamps++;c.history.unshift({type:'stamp',number:c.stamps,at:new Date().toISOString(),seen:false});save()}staffCustomer()};document.querySelectorAll('.redeem').forEach(b=>b.onclick=()=>{const n=+b.dataset.r;if(confirm(`Mark the ${n===5?'25%':'50%'} reward as redeemed for ${c.name}?`)){c.redeemed[n]=true;c.history.unshift({type:'redeem',label:`${n===5?'25%':'50%'} reward redeemed`,at:new Date().toISOString()});save();staffCustomer()}});$('#view').onclick=customer;$('#back').onclick=()=>staff()}
// One-time migration from V0.2 so the tester does not lose the original customer.
if(!db.customers.length){try{const old=JSON.parse(localStorage.getItem('shernzz-demo')||'null');if(old&&old.name){const c=newCustomer(old.name,old.phone);c.stamps=old.stamps||0;c.history=(old.history||[]).map((at,i)=>({type:'stamp',number:i+1,at:new Date(at).toISOString(),seen:true}));save()}}catch(e){}}
current()?customer():join();
